# CMake generated Testfile for 
# Source directory: /root/ros-vision-opencv-1.13.0+ds/cv_bridge/test
# Build directory: /root/ros-vision-opencv-1.13.0+ds/obj-x86_64-linux-gnu/cv_bridge/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_cv_bridge_gtest_cv_bridge-utest "/root/ros-vision-opencv-1.13.0+ds/obj-x86_64-linux-gnu/catkin_generated/env_cached.sh" "/usr/bin/python3" "/usr/share/catkin/cmake/test/run_tests.py" "/root/ros-vision-opencv-1.13.0+ds/obj-x86_64-linux-gnu/test_results/cv_bridge/gtest-cv_bridge-utest.xml" "--return-code" "/root/ros-vision-opencv-1.13.0+ds/obj-x86_64-linux-gnu/devel/lib/cv_bridge/cv_bridge-utest --gtest_output=xml:/root/ros-vision-opencv-1.13.0+ds/obj-x86_64-linux-gnu/test_results/cv_bridge/gtest-cv_bridge-utest.xml")
set_tests_properties(_ctest_cv_bridge_gtest_cv_bridge-utest PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/catkin/cmake/test/tests.cmake;143;add_test;/usr/share/catkin/cmake/test/gtest.cmake;89;catkin_run_tests_target;/usr/share/catkin/cmake/test/gtest.cmake;28;_catkin_add_google_test;/root/ros-vision-opencv-1.13.0+ds/cv_bridge/test/CMakeLists.txt;6;catkin_add_gtest;/root/ros-vision-opencv-1.13.0+ds/cv_bridge/test/CMakeLists.txt;0;")
add_test(_ctest_cv_bridge_nosetests_enumerants.py "/root/ros-vision-opencv-1.13.0+ds/obj-x86_64-linux-gnu/catkin_generated/env_cached.sh" "/usr/bin/python3" "/usr/share/catkin/cmake/test/run_tests.py" "/root/ros-vision-opencv-1.13.0+ds/obj-x86_64-linux-gnu/test_results/cv_bridge/nosetests-enumerants.py.xml" "--return-code" "\"/usr/bin/cmake\" -E make_directory /root/ros-vision-opencv-1.13.0+ds/obj-x86_64-linux-gnu/test_results/cv_bridge" "/usr/bin/nosetests3 -P --process-timeout=60 /root/ros-vision-opencv-1.13.0+ds/cv_bridge/test/enumerants.py --with-xunit --xunit-file=/root/ros-vision-opencv-1.13.0+ds/obj-x86_64-linux-gnu/test_results/cv_bridge/nosetests-enumerants.py.xml")
set_tests_properties(_ctest_cv_bridge_nosetests_enumerants.py PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/catkin/cmake/test/tests.cmake;143;add_test;/usr/share/catkin/cmake/test/nosetests.cmake;83;catkin_run_tests_target;/root/ros-vision-opencv-1.13.0+ds/cv_bridge/test/CMakeLists.txt;13;catkin_add_nosetests;/root/ros-vision-opencv-1.13.0+ds/cv_bridge/test/CMakeLists.txt;0;")
add_test(_ctest_cv_bridge_nosetests_conversions.py "/root/ros-vision-opencv-1.13.0+ds/obj-x86_64-linux-gnu/catkin_generated/env_cached.sh" "/usr/bin/python3" "/usr/share/catkin/cmake/test/run_tests.py" "/root/ros-vision-opencv-1.13.0+ds/obj-x86_64-linux-gnu/test_results/cv_bridge/nosetests-conversions.py.xml" "--return-code" "\"/usr/bin/cmake\" -E make_directory /root/ros-vision-opencv-1.13.0+ds/obj-x86_64-linux-gnu/test_results/cv_bridge" "/usr/bin/nosetests3 -P --process-timeout=60 /root/ros-vision-opencv-1.13.0+ds/cv_bridge/test/conversions.py --with-xunit --xunit-file=/root/ros-vision-opencv-1.13.0+ds/obj-x86_64-linux-gnu/test_results/cv_bridge/nosetests-conversions.py.xml")
set_tests_properties(_ctest_cv_bridge_nosetests_conversions.py PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/catkin/cmake/test/tests.cmake;143;add_test;/usr/share/catkin/cmake/test/nosetests.cmake;83;catkin_run_tests_target;/root/ros-vision-opencv-1.13.0+ds/cv_bridge/test/CMakeLists.txt;14;catkin_add_nosetests;/root/ros-vision-opencv-1.13.0+ds/cv_bridge/test/CMakeLists.txt;0;")
add_test(_ctest_cv_bridge_nosetests_python_bindings.py "/root/ros-vision-opencv-1.13.0+ds/obj-x86_64-linux-gnu/catkin_generated/env_cached.sh" "/usr/bin/python3" "/usr/share/catkin/cmake/test/run_tests.py" "/root/ros-vision-opencv-1.13.0+ds/obj-x86_64-linux-gnu/test_results/cv_bridge/nosetests-python_bindings.py.xml" "--return-code" "\"/usr/bin/cmake\" -E make_directory /root/ros-vision-opencv-1.13.0+ds/obj-x86_64-linux-gnu/test_results/cv_bridge" "/usr/bin/nosetests3 -P --process-timeout=60 /root/ros-vision-opencv-1.13.0+ds/cv_bridge/test/python_bindings.py --with-xunit --xunit-file=/root/ros-vision-opencv-1.13.0+ds/obj-x86_64-linux-gnu/test_results/cv_bridge/nosetests-python_bindings.py.xml")
set_tests_properties(_ctest_cv_bridge_nosetests_python_bindings.py PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/catkin/cmake/test/tests.cmake;143;add_test;/usr/share/catkin/cmake/test/nosetests.cmake;83;catkin_run_tests_target;/root/ros-vision-opencv-1.13.0+ds/cv_bridge/test/CMakeLists.txt;15;catkin_add_nosetests;/root/ros-vision-opencv-1.13.0+ds/cv_bridge/test/CMakeLists.txt;0;")
